### ISSUE TITLE
logging info or verbose control support

### ISSUE THREAD

**Issue by ShixiangWang** [r-lib/cli#369] opened 2021-11-02 14:16 UTC
Hi rlib team,

Thanks for developing this nice tool. I am wondering if this tool can support a switch for verbose control. It's very common to set a `verbose` in functions of an R package. If I implement this in my own, it will end up many `if` checks in functions with many `cli_*` like:

```R
if (getOptions("package.verbose")) cli_alert_info(...)
```

I don't know if there could be a global control that all `cli_*` functions can identify it.

e.g.

```
f = function(x, y, z, verbose = TRUE) {
  if (verbose) set_cli_verbose(TRUE)
 
  # Now all cli_* function will auto detect the cli_verbose and decide if print message
  cli_alert_info(...)
  cli_alert_warn(...)
  ...
}
```

Go further, there could be a logging level like 1, 2, 3 to control different print levels.

Best,

Shixiang

**Comment by gaborcsardi** [comment] 2021-11-02 14:45
I believe that this is a duplicate of #126.

**Closed by gaborcsardi** 2021-11-02 14:45 UTC

**Comment by ShixiangWang** [comment] 2021-11-02 14:49
@gaborcsardi Ohh. Sorry, I searched verbose and did not find anything, so I post a new one.
Thanks for pointing out. :)
