### ISSUE TITLE
Minor bug in documentation

### ISSUE THREAD

**Issue by sda030** [r-lib/cli#515] opened 2022-08-28 10:45 UTC
Output images seem incorrectly placed from the third entry onwards, in "Lists" in [Semantic-CLI#Lists](https://cli.r-lib.org/articles/semantic-cli.html#Lists).

**Comment by gaborcsardi** [comment] 2022-08-28 12:27
Duplicate of #435 I believe.

**Closed by gaborcsardi** 2022-08-28 12:27 UTC
