### ISSUE TITLE
Incorrect outputs displayed in semantic CLI article

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/cli#487] opened 2022-06-20 18:28 UTC
Both on release and devel version of the website, the Semantic CLI [article](https://cli.r-lib.org/dev/articles/semantic-cli.html#cli-messages) is displaying incorrect outputs.

It starts from this code snippet:

<img width="803" alt="Screenshot 2022-06-20 at 20 21 59" src="https://user-images.githubusercontent.com/11330453/174659621-cbf60e35-5732-4c6b-bc35-25f14f3235f0.png">

And then all the following code snippets are accompanied by (off by one) incorrect output:

<img width="842" alt="Screenshot 2022-06-20 at 20 25 43" src="https://user-images.githubusercontent.com/11330453/174660092-5f17b126-6994-43c2-a9a0-5ee1f3b5847a.png">

etc.

**Comment by gaborcsardi** [comment] 2022-06-20 19:05
Duplicate of #435?

**Closed** 2022-06-20 19:07 UTC
